In [1]:
import pandas as pd

In [2]:
df_gap_minder = pd.read_csv('../datasets/gapminder_full.csv')
df_health_expenditure = pd.read_csv('../datasets/health_expenditure.csv')
df_literancy_rate = pd.read_csv('../datasets/literancy_rate.csv')
df_mortality_rate = pd.read_csv('../datasets/mortality_rate.csv')
df_gpd = pd.read_csv('../datasets/gpd.csv')
df_drinking_water = pd.read_csv('../datasets/drinking_water.csv')

Fonte de dados retiradas do https://data.worldbank.org/ os dados utilizados do gap_minder são inicialmente de 1952 o worldbank possui dados a partir de 1960
- Podemos utilizar uma analise a partir de 1960 até 2007

In [3]:
df_gap_minder.head(3)

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710

In [4]:
#df_health_expenditure.head(3)
# df_life_expectancy.head(3)
#df_drinking_water.head(3)
df_gpd.head(3)
#df_mortality_rate.head(3)

,country,country_code,indicator_name,indicator_code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN,NaN

In [5]:
#remover coluna indicator_code de todos os dataframes para manter apenas as colunas necessárias para a aná

def remove_column(df,  list_columns):
    for column_name in list_columns:
        if column_name in df.columns:
            df = df.drop(columns=[column_name])
    return df 

#padronização do country de todos os dataframes removendo espaços e deixando apenas a primeira letra maiúscula para facilitar o merge dos dataframes
def standardize_column(df, column_name):
    df[column_name] = df[column_name].str.strip().str.title()
    return df 

#transformar os dataframes de formato largo para formato longo usando a função melt 
def transform_df_melt(df, list_columns, long_column, value_name):
    df = df.melt(
        id_vars=list_columns,
        var_name=long_column,
        value_name=value_name
    )
    return df

In [6]:
#chama o a função remove_column para remover a coluna indicator_code de todos os dataframes

df_health_expenditure = remove_column(df_health_expenditure, ['indicator_name','indicator_code', 'country_code', 'Unnamed: 70'])
df_gpd = remove_column(df_gpd, ['indicator_name','indicator_code', 'country_code', 'Unnamed: 70'])  
df_drinking_water = remove_column(df_drinking_water, ['indicator_name','indicator_code', 'country_code', 'Unnamed: 70'])
df_literancy_rate = remove_column(df_literancy_rate, ['indicator_name','indicator_code', 'country_code', 'Unnamed: 70'])
df_mortality_rate = remove_column(df_mortality_rate, ['indicator_name','indicator_code', 'country_code', 'Unnamed: 70'])

In [7]:
#chama o a função standardize_column para padronizar a coluna country de todos os dataframes
column_name = 'country'

df_gap_minder = standardize_column(df_gap_minder, column_name)
df_health_expenditure = standardize_column(df_health_expenditure, column_name)
df_gpd = standardize_column(df_gpd, column_name)
df_drinking_water = standardize_column(df_drinking_water, column_name)
df_literancy_rate = standardize_column(df_literancy_rate, column_name)
df_mortality_rate = standardize_column(df_mortality_rate, column_name)

In [8]:
#chama a função transform_df_melt para transformar os dataframes de formato largo para formato longo
list_columns=["country"]
long_column = 'year'

value_name = 'health_expenditure'
df_health_expenditure = transform_df_melt(df_health_expenditure, list_columns, long_column, value_name)

value_name = 'gpd'
df_gpd = transform_df_melt(df_gpd, list_columns, long_column, value_name)

value_name = 'drinking_water'
df_drinking_water = transform_df_melt(df_drinking_water, list_columns, long_column, value_name)

value_name = 'literancy_rate'
df_literancy_rate = transform_df_melt(df_literancy_rate, list_columns, long_column, value_name)

value_name = 'mortality_rate'
df_mortality_rate = transform_df_melt(df_mortality_rate, list_columns, long_column, value_name)

In [9]:
df_health_expenditure['year'] = df_health_expenditure['year'].astype(int)

df_gpd['year'] = df_gpd['year'].astype(int)

df_drinking_water['year'] = df_drinking_water['year'].astype(int)

df_literancy_rate['year'] = df_literancy_rate['year'].astype(int)

df_mortality_rate['year'] = df_mortality_rate['year'].astype(int)

In [10]:
#df_health_expenditure.head(3)
#df_literancy_rate.head(3)
df_mortality_rate.head(3)

                       country  year  mortality_rate
0                        Aruba  1960             NaN
1  Africa Eastern And Southern  1960             NaN
2                  Afghanistan  1960           252.4

In [11]:
df_gap_minder = df_gap_minder.merge(df_health_expenditure, on=['country', 'year'], how='left')
df_gap_minder = df_gap_minder.merge(df_gpd, on=['country', 'year'], how='left')
df_gap_minder = df_gap_minder.merge(df_drinking_water, on=['country', 'year'], how='left')
df_gap_minder = df_gap_minder.merge(df_literancy_rate, on=['country', 'year'], how='left')
df_gap_minder = df_gap_minder.merge(df_mortality_rate, on=['country', 'year'], how='left')

#dividino o gpd por 1 bilhão para facilitar a visualização dos dados
df_gap_minder['gpd_trilhoes'] = (df_gap_minder['gpd'] / 1_000_000_000).round(2)

In [12]:
df_gap_minder[df_gap_minder['country'] == 'Brazil']

,country,year,pop,continent,lifeExp,gdpPercap,health_expenditure,gpd,drinking_water,literancy_rate,mortality_rate,gpd_trilhoes
175,Brazil,1952,56602560.0,Americas,50.917,2108.944355,NaN,NaN,NaN,NaN,NaN,NaN
176,Brazil,1957,65551171.0,Americas,53.285,2487.365989,NaN,NaN,NaN,NaN,NaN,NaN
177,Brazil,1962,76039390.0,Americas,55.665,3336.585802,NaN,1.923175e+10,NaN,NaN,120.8,19.23
178,Brazil,1967,88049823.0,Americas,57.632,3429.864357,NaN,3.108639e+10,NaN,NaN,108.5,31.09
179,Brazil,1972,100840058.0,Americas,59.504,4985.711467,NaN,5.843486e+10,NaN,NaN,97.9,58.43
180,Brazil,1977,114313951.0,Americas,61.489,6660.118654,NaN,1.763441e+11,NaN,NaN,85.7,176.34
181,Brazil,1982,128962939.0,Americas,63.336,7030.835878,NaN,2.713141e+11,NaN,NaN,70.4,271.31
182,Brazil,1987,142938076.0,Americas,65.205,7807.095818,NaN,2.830568e+11,NaN,NaN,58.1,283.06
183,Brazil,1992,155975974.0,Americas,67.057,6950.283021,NaN,3.281880e+11,NaN,NaN,47.4,328.19
184,Brazil,1997,168546719.0,Americas,69.388,7957.980824,NaN,8.832065e+11,NaN,NaN,35.2,883.21
185,Brazil,2002,179914212.0,Americas,71.006,8131.212843,8.69687,5.097953e+11,94.186428,NaN,25.6,509.80
186,Brazil,2007,190010647.0,Americas,72.390,9065.800825,8.20183,1.397114e+12,95.661956,90.010002,18.6,1397.11

In [13]:
df_gap_minder.to_csv('../datasets/gap_minder_merged.csv', index=False)

In [14]:
df_gap_minder.info()

<class 'pandas.DataFrame'>
RangeIndex: 1736 entries, 0 to 1735
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             1736 non-null   str
 1   year                1736 non-null   int64
 2   pop                 1736 non-null   float64
 3   continent           1736 non-null   str
 4   lifeExp             1736 non-null   float64
 5   gdpPercap           1736 non-null   float64
 6   health_expenditure  250 non-null    float64
 7   gpd                 1121 non-null   float64
 8   drinking_water      247 non-null    float64
 9   literancy_rate      57 non-null     float64
 10  mortality_rate      1174 non-null   float64
 11  gpd_trilhoes        1121 non-null   float64
dtypes: float64(9), int64(1), str(2)
memory usage: 162.9 KB